import "@/styles/globals.css";
import type { Metadata } from "next";
import { Geist, Geist_Mono, Kaisei_Tokumin } from "next/font/google";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const KaiseiTokumin = Kaisei_Tokumin({
  variable: "--font-kaisei-tokumin",
  weight: ["400", "500", "700", "800"],
  subsets: ["latin"],
  display: "swap",
  style: "normal",
  fallback: ["sans-serif"],
  preload: true,
  adjustFontFallback: true,
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${KaiseiTokumin.variable} ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
